import { createClient } from '@supabase/supabase-js';
import * as SecureStore from 'expo-secure-store';
import { Platform } from 'react-native';

const supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseAnonKey) {
    console.warn('Supabase credentials not configured. Please add to .env file.');
}

// Expo SecureStore adapter for React Native
const ExpoSecureStoreAdapter = {
    getItem: (key: string) => {
        return SecureStore.getItemAsync(key);
    },
    setItem: (key: string, value: string) => {
        SecureStore.setItemAsync(key, value);
    },
    removeItem: (key: string) => {
        SecureStore.deleteItemAsync(key);
    },
};

// Create Supabase client
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
    auth: {
        storage: Platform.OS === 'web' ? undefined : ExpoSecureStoreAdapter,
        autoRefreshToken: true,
        persistSession: true,
        detectSessionInUrl: false,
    },
});

// Database types (auto-generated by Supabase)
export type Profile = {
    id: string;
    email: string | null;
    name: string | null;
    picture: string | null;
    role: 'user' | 'premium' | 'coach';
    created_at: string;
    updated_at: string;
};

export type ValidationCard = {
    id: string;
    message_es: string;
    message_en: string | null;
    category: string;
    created_at: string;
};

export type CheckIn = {
    id: string;
    user_id: string;
    mood: 1 | 2 | 3;
    sleep_start: string | null;
    sleep_end: string | null;
    baby_wakeups: number | null;
    brain_dump: string | null;
    ai_response: string | null;
    created_at: string;
};

export type ChatMessage = {
    id: string;
    session_id: string;
    user_id: string;
    role: 'user' | 'assistant';
    content: string;
    created_at: string;
};

export type DirectMessage = {
    id: string;
    sender_id: string;
    receiver_id: string;
    content: string;
    read: boolean;
    created_at: string;
};

export type Bitacora = {
    id: string;
    user_id: string;
    day_number: number;
    date: string;
    ai_summary: string | null;
    created_at: string;
    updated_at: string;
    // Add other fields as needed
};
